### ISSUE TITLE
How do i install this

### ISSUE THREAD

**Issue by TigerIS2025** [playsamay4/BBCD3_Desktop#1]
And also how can i program "viz 2.0" to OBS Studio?

**Comment by playsamay4** [comment]
[Navigate to releases](https://github.com/playsamay4/BBCD3_Desktop/releases/) and download the latest .zip file. run the exe you do not need to install it.
as for viz you need to create a Game Capture source, enable capturing transparency in its settings then point it to the viz 2.0 window
